# --- H2 Database Configuration (In-Memory) ---
# Use H2 database
spring.datasource.url=jdbc:h2:file:./target/h2-database/mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# --- JPA Configuration ---
# This allows JPA to automatically create/update your tables (like network_packets)
spring.jpa.hibernate.ddl-auto=update
# Show SQL in the console for debugging
spring.jpa.show-sql=true

# --- H2 Console (Optional, but very useful) ---
# Enable the H2 web console
spring.h2.console.enabled=true
# Set the path to access the console (e.g., http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console

# --- Spring Mail Configuration ---
# --- Spring Mail Configuration (for Ethereal.email) ---

# The Ethereal SMTP Server (NOT your email address)
spring.mail.host=smtp.ethereal.email

# The Port (587 is correct for TLS)
spring.mail.port=587

# Your full Ethereal USERNAME (the email address)
spring.mail.username=ima86@ethereal.email

# Your Ethereal PASSWORD
spring.mail.password=3tdbgj6SGa3vtpFhw3


# --- SMTP Server Properties ---
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Custom App Properties ---
alert.admin.email=alerts@my-dashboard.com

# --- AbuseIPDB Threat Intelligence Configuration ---
# Paste your API key from the AbuseIPDB website
abuseipdb.api.key=98ae71b0d3ad67c23f5b261c453095450e1dbb5f6fc7fbeedf9dfbb9785a14b44209965f452cd06c
# --- Secret key for encryption ---
encryption.password=your-super-secret-password-123!

# =======================================================
# ==           KEYSTORE ENCRYPTION SETTINGS            ==
# =======================================================
# --- KeyStore Properties ---
# The path to your "safe" (use forward slashes)
keystore.path=C:/my-secrets/keystore.p12

# The password you created for the "safe"
keystore.password=vaipillaraja

# The name of the "key" inside the "safe"
keystore.key.alias=my-enc-key

# The format of the "safe"
keystore.type=PKCS12


# =======================================================
# ==              ADMIN USER SETTINGS                  ==
# =======================================================
# (You can change these values)
admin.username=vitvellore
admin.password=hellovit


